# Generated by Django 4.1.2 on 2022-11-06 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('moving_time', models.DurationField()),
                ('elapsed_time', models.DurationField()),
                ('total_elevation_gain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_cadence', models.DecimalField(decimal_places=2, max_digits=6)),
                ('has_heartrate', models.BooleanField()),
                ('average_heartrate', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('max_heartrate', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('activity_logged_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
