# Generated by Django 4.1.2 on 2022-11-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_activityobject_delete_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='average_cadence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='activityobject',
            name='average_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='activityobject',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
