# Generated by Django 4.1.2 on 2022-11-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_alter_activityobject_average_cadence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='has_heartrate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
