# Generated by Django 4.1.2 on 2022-11-06 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0005_alter_activityobject_has_heartrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='activity_logged_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
