# Generated by Django 4.1.2 on 2022-11-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0007_alter_activityobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
