# Generated by Django 4.1.2 on 2022-11-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0008_alter_activityobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityobject',
            name='average_speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='activityobject',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='activityobject',
            name='total_elevation_gain',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
